<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>ecommerce_flashsale_backend.Infrastructure</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ecommerce-flashsale-backend.Domain\ecommerce-flashsale-backend.Domain.csproj" />
    <ProjectReference Include="..\ecommerce-flashsale-backend.Application\ecommerce-flashsale-backend.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Migrations\" />
    <Folder Include="Persistence\Repositories\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.18" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.18" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.18" />
    <PackageReference Include="StackExchange.Redis" Version="3.0.17" />
  </ItemGroup>

</Project>
